version: '3.8'
services:
    frontend:
        build: ./src/frontend
        ports: 
            - "8080:80"
    api:
        build:
            dockerfile: ./.dockerbuild/dockerfile-api
        ports:
            - "8081:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
    service:
        build: 
            dockerfile: ./.dockerbuild/dockerfile-service
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    postgres:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - '5432:5432'
        volumes: 
            - ./.data/postgres:/var/lib/postgresql/data
    
    influx:
        image: influxdb
        restart: always
        volumes:
            - ./.data/.influx:/var/lib/influxdb2:rw
        ports:
            - "8086:8086"
    
    rabbit:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./.data/rabbitmq:/var/lib/rabbitmq/
            - ./.data/rabbitmq:/var/log/rabbitmq/