FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS builder

WORKDIR /app
COPY ../src/Api/Api.csproj ./Api/
COPY ../src/Contracts/Contracts.csproj ./Contracts/
COPY ../src/Core/Core.csproj ./Core/
RUN dotnet restore ./Api/Api.csproj --no-cache --force

COPY ../src/Api/ ./Api/
COPY ../src/Contracts/ ./Contracts/
COPY ../src/Core/ ./Core/

RUN dotnet publish ./Api/Api.csproj -c Release -o out --self-contained true 

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine AS prod
WORKDIR /app
COPY --from=builder /app/out .

EXPOSE 80
ENTRYPOINT ["./Api"]